### Get all objects
GET http://localhost:3000/api/

### Create a new object
POST http://localhost:3000/api/
Content-Type: application/json

{
  "name": "obababab",
  "protein": 11 ,
  "calories": 111
}

### Update a object
PUT  http://localhost:3000/api/0
Content-Type: application/json

{
  "name": "abc",
  "protein": 100,
  "calories": 222
}

### Delete a specified object
DELETE  http://localhost:3000/api/0

### GET a specified object
GET   http://localhost:3000/api/1
